# Generated by Django 3.1.3 on 2020-11-13 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.PositiveSmallIntegerField(default=11, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
    ]
